### ISSUE TITLE
Consider using FindBinary instead of TryFindBinary, and review clean-up logic

### ISSUE THREAD

**Issue by DominicCronin** [sdl/dxa-web-application-dotnet#21] opened 2016-06-24 13:55 UTC
At https://github.com/sdl/dxa-web-application-dotnet/blob/master/Sdl.Web.Tridion/Statics/BinaryFileManager.cs#L166 there is a comment in the code, indicating that DD4T's behaviour is not as expected. 

Reviewing the code at (and nearby) https://github.com/dd4t/DD4T.Core/blob/develop/source/DD4T.Factories/BinaryFactory.cs#L49 you can see that there is a FindBinary method which will test the boolean from TryFindBinary and throw if false. 

Note also that the code at https://github.com/sdl/dxa-web-application-dotnet/blob/master/Sdl.Web.Tridion/Statics/BinaryFileManager.cs#L158 will not clean up in the way that the code at L169 does. 

That said, the DD4T code isn't as clear as it might be. If using the obsolete streaming approach, you would not expect BinaryData to be available.

**Comment by rpannekoek** [comment] 2016-07-06 14:47
Hi Dominic.  Can you clarify what you think the Issue is in DXA codebase, exactly?

**Comment by DominicCronin** [comment] 2016-07-06 19:25
Hi Rick, 

The key is in my use of the word "Consider". I'm pointing out inconsistencies rather than saying something is 100% broken. In the meantime, I've learned that the DD4T develop branch has changes that have yet to impact DXA, so perhaps it can/should wait a bit. So take this as a flag that this area needs an architectural review (probably from both DD4T and DXA) as much as a code review. The responsibility for handing back a cleanly obtained binary, or failing, should probably lie with DD4T, and DXA should be able to trust that. Personally, I'd put the responsibility for file system caching (or caching generally) in DD4T. As it is, DXA has an inconsistency. 
Obviously, as the two projects come under common governance, this kind of thing ought to be easier. (It will also be easier if DD4T can get rid of the obsolete streaming approach, giving clearer expectations at the API.)

**Comment by rpannekoek** [comment] 2016-12-22 20:12
Fixed in DXA 1.7; refactored `BinaryFileManager` to retrieve Binaries directly from CD API.

**Closed by rpannekoek** 2016-12-22 20:12 UTC
